import { ThemeConfig } from '@/types/resume';

export const presetThemes: ThemeConfig[] = [
  // 基础主题
  {
    id: 'modern',
    name: '现代蓝',
    primaryColor: '#3b82f6',
    secondaryColor: '#64748b',
    backgroundColor: '#ffffff',
    textColor: '#1f2937',
    fontFamily: 'sans',
    fontSize: 'medium',
    layout: 'single',
  },
  {
    id: 'classic',
    name: '经典黑',
    primaryColor: '#1a1a1a',
    secondaryColor: '#4a4a4a',
    backgroundColor: '#ffffff',
    textColor: '#333333',
    fontFamily: 'serif',
    fontSize: 'medium',
    layout: 'single',
  },
  {
    id: 'elegant',
    name: '优雅紫',
    primaryColor: '#7c3aed',
    secondaryColor: '#a78bfa',
    backgroundColor: '#faf5ff',
    textColor: '#1f2937',
    fontFamily: 'sans',
    fontSize: 'medium',
    layout: 'single',
  },
  {
    id: 'professional',
    name: '专业绿',
    primaryColor: '#059669',
    secondaryColor: '#10b981',
    backgroundColor: '#ffffff',
    textColor: '#1f2937',
    fontFamily: 'sans',
    fontSize: 'medium',
    layout: 'single',
  },
  {
    id: 'creative',
    name: '创意橙',
    primaryColor: '#ea580c',
    secondaryColor: '#fb923c',
    backgroundColor: '#fffbeb',
    textColor: '#1f2937',
    fontFamily: 'sans',
    fontSize: 'medium',
    layout: 'single',
  },
  {
    id: 'minimal',
    name: '极简灰',
    primaryColor: '#475569',
    secondaryColor: '#94a3b8',
    backgroundColor: '#ffffff',
    textColor: '#334155',
    fontFamily: 'sans',
    fontSize: 'small',
    layout: 'single',
  },
  // 双栏主题
  {
    id: 'sidebar-blue',
    name: '双栏蓝',
    primaryColor: '#2563eb',
    secondaryColor: '#60a5fa',
    backgroundColor: '#ffffff',
    textColor: '#1e293b',
    fontFamily: 'sans',
    fontSize: 'medium',
    layout: 'double',
  },
  {
    id: 'sidebar-dark',
    name: '双栏深',
    primaryColor: '#0f172a',
    secondaryColor: '#475569',
    backgroundColor: '#ffffff',
    textColor: '#1e293b',
    fontFamily: 'sans',
    fontSize: 'medium',
    layout: 'double',
  },
  {
    id: 'sidebar-teal',
    name: '双栏青',
    primaryColor: '#0d9488',
    secondaryColor: '#2dd4bf',
    backgroundColor: '#f0fdfa',
    textColor: '#134e4a',
    fontFamily: 'sans',
    fontSize: 'medium',
    layout: 'double',
  },
  // 特色主题
  {
    id: 'tech',
    name: '科技感',
    primaryColor: '#06b6d4',
    secondaryColor: '#22d3ee',
    backgroundColor: '#f8fafc',
    textColor: '#0f172a',
    fontFamily: 'sans',
    fontSize: 'medium',
    layout: 'single',
  },
  {
    id: 'warm',
    name: '暖色调',
    primaryColor: '#dc2626',
    secondaryColor: '#f87171',
    backgroundColor: '#fef2f2',
    textColor: '#1f2937',
    fontFamily: 'sans',
    fontSize: 'medium',
    layout: 'single',
  },
  {
    id: 'nature',
    name: '自然绿',
    primaryColor: '#16a34a',
    secondaryColor: '#4ade80',
    backgroundColor: '#f0fdf4',
    textColor: '#14532d',
    fontFamily: 'sans',
    fontSize: 'medium',
    layout: 'single',
  },
  {
    id: 'ocean',
    name: '海洋蓝',
    primaryColor: '#0284c7',
    secondaryColor: '#38bdf8',
    backgroundColor: '#f0f9ff',
    textColor: '#0c4a6e',
    fontFamily: 'sans',
    fontSize: 'medium',
    layout: 'single',
  },
  {
    id: 'rose',
    name: '玫瑰粉',
    primaryColor: '#e11d48',
    secondaryColor: '#fb7185',
    backgroundColor: '#fff1f2',
    textColor: '#1f2937',
    fontFamily: 'sans',
    fontSize: 'medium',
    layout: 'single',
  },
  {
    id: 'sunset',
    name: '日落橘',
    primaryColor: '#c2410c',
    secondaryColor: '#f97316',
    backgroundColor: '#fff7ed',
    textColor: '#431407',
    fontFamily: 'sans',
    fontSize: 'medium',
    layout: 'single',
  },
  {
    id: 'lavender',
    name: '薰衣草',
    primaryColor: '#7e22ce',
    secondaryColor: '#a855f7',
    backgroundColor: '#faf5ff',
    textColor: '#3b0764',
    fontFamily: 'serif',
    fontSize: 'medium',
    layout: 'single',
  },
];

export const defaultTheme = presetThemes[0]; // modern
